#!/usr/bin/env python3
"""
Generates an animated terminal-style GitHub profile card (dark.svg + light.svg).

Everything you'd normally want to tweak lives in CONFIG / ASCII_ART / INFO below.
Stats (repos, stars, followers) are pulled live from the GitHub API when the
script runs in Actions; if the API is unreachable it silently falls back.
"""

import json
from json.tool import main
import os
import urllib.request
from datetime import datetime, timezone, timedelta
from html import escape
from pathlib import Path

# ----------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------
USERNAME = "AJKakarot"  # GitHub username (used for stats fetch + profile link)

PORTRAIT_FILE = "portrait.txt"   # generated by photo_to_ascii.py

def load_portrait():
    f = Path(__file__).parent / PORTRAIT_FILE
    if f.exists():
        return f.read_text(encoding="utf-8").rstrip("\n").split("\n")
    return ["[ portrait.txt missing ]"]


# (label, value, colour-key)  |  colour-key: key / val / accent / warn / muted
INFO = [
    ("__header__", "Ajeet Gupta", ""),
    ("__rule__", "", ""),

    ("__section__", "~/experience", ""),

    ("Intern", "React Developer @ TMRW", "val"),
    ("Intern", "Cloud Computing @ IBM", "val"),
    ("Intern", "Development @ Modulus", "val"),
    ("Community", "GeeksforGeeks Campus Mantri", "accent"),
    
    ("__blank__", "", ""),
    ("__section__", "~/skills", ""),

    ("Backend", "Java • Spring Boot • Node.js • Express", "val"),
    ("AI", "LangChain • LangGraph • Agentic AI • RAG", "val"),
    ("Cloud", "AWS • Docker • PostgreSQL • Redis", "val"),

    ("__blank__", "", ""),
    ("__section__", "~/projects", ""),

   ("Projects", "Wellory • AI-Coach • AI-Interview • NextHire", "warn"),

    ("__blank__", "", ""),
    ("__section__", "~/highlights", ""),

    ("Coding", "365 Days of Code • 1000+ DSA", "val"),
    ("Hackathons", "2× Hackathon Winner", "val"),

    ("__blank__", "", ""),
    ("__section__", "~/connect", ""),

    ("GitHub", "github.com/AJKakarot", "accent"),
    ("LinkedIn", "linkedin.com/in/ajeet-gupta-99aa6b281", "accent"),
    ("LeetCode", "leetcode.com/u/ajeetgupta04", "accent"),
    ("Email", "gajeet031@gmail.com", "accent"),
]

THEMES = {
    "dark": {
    "bg": "#0d1117",
    "panel": "#161b22",
    "border": "#30363d",

    "text": "#c9d1d9",
    "muted": "#8b949e",

    "key": "#3fb950",
    "accent": "#58a6ff",
    "warn": "#d29922",

    "art": "#c9d1d9",   # Changed (Grey)

    "prompt": "#3fb950",
    "dot1": "#ff5f56",
    "dot2": "#ffbd2e",
    "dot3": "#27c93f",
    },
    "light": {
    "bg": "#ffffff",
    "panel": "#f6f8fa",
    "border": "#d0d7de",

    "text": "#1f2328",
    "muted": "#59636e",

    "key": "#1a7f37",
    "accent": "#0969da",
    "warn": "#9a6700",

    "art": "#57606a",   # Changed

    "prompt": "#1a7f37",
    "dot1": "#ff5f56",
    "dot2": "#ffbd2e",
    "dot3": "#27c93f",
     },
}

W, H = 980, 620
ART_X, ART_Y = 0, 86
ART_CW = 3.9          # forced char width (textLength keeps this exact in any font)
ART_LH = ART_CW * 1.72
INFO_X, INFO_Y, INFO_LH = 448, 92, 17.5
VAL_X = INFO_X + 92


# ----------------------------------------------------------------------------
# 
# ----------------------------------------------------------------------------
# RENDER
# ----------------------------------------------------------------------------
def render(theme_name, colors, stats, ist_now):
    art_lines = load_portrait()

    parts = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" font-family="ui-monospace, SFMono-Regular, '
        f'\'JetBrains Mono\', \'Cascadia Code\', Menlo, Consolas, monospace">'
    )

    # styles + animations
    parts.append(f"""<style>
    .art  {{ fill:{colors['art']}; font-size:6.2px; white-space:pre; }}
    .key  {{ fill:{colors['key']}; font-size:13px; font-weight:700; }}
    .val  {{ fill:{colors['text']}; font-size:13px; }}
    .acc  {{ fill:{colors['accent']}; font-size:13px; }}
    .wrn  {{ fill:{colors['warn']}; font-size:13px; }}
    .mut  {{ fill:{colors['muted']}; font-size:12px; }}
    .hdr  {{ fill:{colors['accent']}; font-size:15px; font-weight:700; }}
    .sec  {{ fill:{colors['muted']}; font-size:12px; letter-spacing:1px; }}
    .ttl  {{ fill:{colors['muted']}; font-size:12px; }}
    .row  {{ opacity:1; animation: fade .35s ease backwards; }}
    @keyframes fade {{ from {{ opacity:0; transform:translateY(3px); }}
                       to   {{ opacity:1; transform:translateY(0); }} }}
    .cur  {{ fill:{colors['prompt']}; animation: blink 1s steps(1) infinite; }}
    @keyframes blink {{ 50% {{ opacity:0; }} }}
    .artline {{ opacity:1; animation: fade .3s ease backwards; }}
    </style>""")

    # window chrome
    parts.append(
        f'<rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" '
        f'fill="{colors["bg"]}" stroke="{colors["border"]}" stroke-width="1.5"/>'
    )
    parts.append(
        f'<path d="M1 13 a12 12 0 0 1 12 -12 h{W-26} a12 12 0 0 1 12 12 v25 h{-(W-2)} z" '
        f'fill="{colors["panel"]}"/>'
    )
    parts.append(f'<line x1="1" y1="38" x2="{W-1}" y2="38" stroke="{colors["border"]}"/>')
    for i, c in enumerate(["dot1", "dot2", "dot3"]):
        parts.append(f'<circle cx="{24 + i*20}" cy="20" r="6" fill="{colors[c]}"/>')
    parts.append(
        f'<text x="{W/2}" y="24" class="ttl" text-anchor="middle">'
        f'{escape(USERNAME)} — zsh — 90×26</text>'
    )

    # command line
    parts.append(
        f'<text x="{ART_X}" y="66" class="row" style="animation-delay:.05s">'
        f'<tspan class="key">➜</tspan>'
        f'<tspan class="acc" dx="8">~</tspan>'
        f'<tspan class="val" dx="8">neofetch --profile</tspan></text>'
    )

    # ascii art
    for i, line in enumerate(art_lines):
        if not line.strip():
            continue
        y = ART_Y + i * ART_LH
        delay = 0.15 + i * 0.012
        tl = len(line) * ART_CW
        parts.append(
            f'<text x="{ART_X}" y="{y:.1f}" class="art artline" xml:space="preserve" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs" '
            f'style="animation-delay:{delay:.2f}s">{escape(line)}</text>'
        )

    # info block
    y = INFO_Y
    delay = 0.35
    cls_map = {"val": "val", "accent": "acc", "warn": "wrn", "muted": "mut"}

    for label, value, ckey in INFO:
        d = f'style="animation-delay:{delay:.2f}s"'
        if label == "__header__":
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="hdr row" {d}>{escape(value)}</text>')
            y += INFO_LH
        elif label == "__rule__":
            parts.append(
                f'<line x1="{INFO_X}" y1="{y-8:.1f}" x2="{W-40}" y2="{y-8:.1f}" '
                f'stroke="{colors["border"]}" class="row" {d}/>'
            )
            y += 8
        elif label == "__blank__":
            y += 10
            continue
        elif label == "__section__":
            parts.append(f'<text x="{INFO_X}" y="{y:.1f}" class="sec row" {d}>{escape(value)}</text>')
            y += INFO_LH
        else:
            cls = cls_map.get(ckey, "val")
            if label:
                parts.append(
                    f'<text x="{INFO_X}" y="{y:.1f}" class="key row" {d}>{escape(label)}</text>'
                )
            parts.append(
                f'<text x="{VAL_X}" y="{y:.1f}" class="{cls} row" {d}>{escape(value)}</text>'
            )
            y += INFO_LH
        delay += 0.07

    # footer prompt + blinking cursor
    fy = H - 24
    parts.append(
        f'<text x="{ART_X}" y="{fy}" class="row" style="animation-delay:{delay+0.1:.2f}s">'
        f'<tspan class="key">➜</tspan>'
        f'<tspan class="acc" dx="8">~</tspan>'
        f'<tspan class="val" dx="8">open to Full Stack AI Engineer / Backend SDE roles</tspan>'
        f'<tspan class="cur" dx="8">█</tspan></text>'
    )
    parts.append(
        f'<text x="{W-34}" y="{fy}" class="mut" text-anchor="end">'
        f'last updated {ist_now}</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts)

def main():
    stats = {}  # क्योंकि तुमने repos/stars/followers हटा दिए हैं

    ist = datetime.now(timezone.utc) + timedelta(hours=5, minutes=30)
    stamp = ist.strftime("%d %b %Y, %H:%M IST")

    out = Path(__file__).parent

    for name, colors in THEMES.items():
        svg = render(name, colors, stats, stamp)
        (out / f"{name}.svg").write_text(svg, encoding="utf-8")
        print(f"wrote {name}.svg")


if __name__ == "__main__":
    main()
